[package]
name = "jib"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
description = "Jib is a library for the Solana blockchain that lets you efficiently pack instructions into transactions and submit them via a TPU client."
repository = "https://github.com/samuelvanderwaal/jib"
readme = "README.md"
keywords = ["solana", "blockchain", "transactions", "instructions", "tpu"]
documentation = "https://docs.rs/jib"
homepage = "https://github.com/samuelvanderwaal/jib"

[dependencies]
bincode = "1.3.3"
solana-client = "~1.14"
solana-sdk = "~1.14"
thiserror = "1.0.40"
tracing = "0.1.37"
